name: Validation
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  changelog:
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04]
        node: [20]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run validate:changelog
      - name: Check for Motoko file changes
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha || 'origin/main' }} HEAD | grep -q '^src/.*\.mo$'; then
            echo "Found modified Motoko files, checking for Changelog.md update..."
            if ! git diff --name-only ${{ github.event.pull_request.base.sha || 'origin/main' }} HEAD | grep -q '^Changelog\.md$'; then
              echo "Error: Motoko files were modified but Changelog.md was not updated"
              exit 1
            fi
          fi

  version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04]
        node: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run validate:version

  docs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04]
        node: [20]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - name: Validate changed files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha || 'origin/main' }} HEAD | grep '^src/.*\.mo$' || true)
          if [ -n "$CHANGED_FILES" ]; then
            echo "$CHANGED_FILES" | xargs npm run validate:docs
          else
            echo "No Motoko files changed"
          fi
        env:
          FORCE_COLOR: 2 # https://github.com/chalk/supports-color/issues/106

  api:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04]
        node: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run validate:api
